13 onboarding flow backend
hatchways/team-pumpkin-spice pull request #19
Opened 2020-02-10 20:51 UTC by rkerins91

Contains user/:id/experience PUT route to update user's experience map, as well as the user model to support a map of experiences for the user. Also updated user registration route to initialize an empty object to experience property on new users.

2020-02-11 02:48 UTC, ashan36 commented on server/routes/user.js
> +      const user = new User({ name, email, experience: {} });
I think this might conflict with my PR a bit. I can easily update it to include an empty experience object.

2020-02-11 02:51 UTC, ashan36 requested changes
I'll update my PR to add the experience object to the new user. If you just remove that part on yours then you can merge it into dev without any conflicts popping up when I merge mine.

2020-02-11 03:28 UTC, rkerins91 commented
> I'll update my PR to add the experience object to the new user. If you just remove that part on yours then you can merge it into dev without any conflicts popping up when I merge mine.

Alright, done.

2020-02-11 03:42 UTC, ashan36 approved these changes

2020-02-11 19:01 UTC, skassam21 commented on server/routes/user.js
> +      await user.experience.set(language, Number(languages[language]));
maybe we should validate languages against a predefined list

Also, is there a way to set it all at once as opposed to doing n calls to the database to set this information on the user? It's not that efficient

2020-02-12 15:36 UTC, skassam21 commented on server/routes/user.js
> +  const availableLanguages = [
probably want this list to be as a constant somewhere else in case we need to reuse it

2020-02-13 18:58 UTC, merged